name: feishu2md_app
description: 飞书文档下载器 - 将飞书文档转换为Markdown格式

# 发布相关配置
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 用于HTTP请求
  http: ^0.13.5
  
  # 用于文件选择
  file_picker: ^5.2.5
  
  # 用于路径操作
  path: ^1.8.2
  
  # Material Design图标
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# Flutter相关配置
flutter:
  uses-material-design: true
